name: go-lint
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Run lints
        run: |
          sudo apt-get install shellcheck
          make lint
