name: release
on:
  push:
    branches:
      - "release"
      - "next"
jobs:
  test:
    uses: ./.github/workflows/go-test.yaml
  lint:
    uses: ./.github/workflows/go-lint.yaml

  release:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
        run: npx semantic-release --debug
